.TH "/Users/thibault/Google Drive/PROG/S4/Projet/cpp Directory Reference" 3 "Mon Apr 24 2017" "Havannah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/thibault/Google Drive/PROG/S4/Projet/cpp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBjeu\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBplateau\&.cpp\fP"
.br
.RI "Fichier source contenant les fonctions de la classe plateau\&. "
.ti -1c
.RI "file \fBplayer\&.cpp\fP"
.br
.in -1c
