.TH "/Users/thibault/Google Drive/PROG/S4/Projet/h/jeu.h" 3 "Mon Apr 24 2017" "Havannah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/thibault/Google Drive/PROG/S4/Projet/h/jeu.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include '\&.\&./h/plateau\&.h'\fP
.br
\fC#include '\&.\&./h/player\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBjeu\fP"
.br
.RI "classe jeu "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Havannah from the source code\&.
