.TH "/Users/thibault/Google Drive/PROG/S4/Projet/cpp/main.cpp" 3 "Mon Apr 24 2017" "Havannah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/thibault/Google Drive/PROG/S4/Projet/cpp/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include '\&.\&./h/jeu\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBmenu\fP ()"
.br
.RI "Fonction affichant le menu au joueur\&. "
.ti -1c
.RI "void \fBlancer_partie\fP ()"
.br
.RI "Fonction permettant de lancer la partie avec les paramètres prédéfinis\&. "
.ti -1c
.RI "void \fBchanger_param\fP ()"
.br
.RI "Fonction permettant de changer les paramètres\&. "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBdefault_taille_plateau\fP = 8"
.br
.RI "Taille par défaut\&. "
.ti -1c
.RI "int \fBdefault_nb_player\fP = 2"
.br
.RI "Nombre de joueurs par défaut\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void changer_param ()"

.PP
Fonction permettant de changer les paramètres\&. 
.SS "void lancer_partie ()"

.PP
Fonction permettant de lancer la partie avec les paramètres prédéfinis\&. 
.SS "int main ()"

.SS "bool menu ()"

.PP
Fonction affichant le menu au joueur\&. 
.SH "Variable Documentation"
.PP 
.SS "int default_nb_player = 2"

.PP
Nombre de joueurs par défaut\&. 
.SS "int default_taille_plateau = 8"

.PP
Taille par défaut\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Havannah from the source code\&.
