.TH "/Users/thibault/Google Drive/PROG/S4/Projet/h/plateau.h" 3 "Wed May 10 2017" "Havannah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/thibault/Google Drive/PROG/S4/Projet/h/plateau.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include '\&./player\&.h'\fP
.br
\fC#include '\&.\&./h/arbre\&.h'\fP
.br
\fC#include '\&.\&./h/noeud\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBplateau\fP"
.br
.RI "classe plateau "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Havannah from the source code\&.
