.TH "/Users/thibault/Google Drive/PROG/S4/Projet/h/player.h" 3 "Mon Apr 24 2017" "Havannah" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/thibault/Google Drive/PROG/S4/Projet/h/player.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <list>\fP
.br
\fC#include '\&.\&./cpp/arbre\&.cpp'\fP
.br
\fC#include '\&.\&./cpp/noeud\&.cpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBplayer\fP"
.br
.RI "class joueur "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Havannah from the source code\&.
